datasource:
  pages:
    list: orders.yaml
    details: products.yaml
    cart: products.yaml

  urls:
    /products: products.yaml
    /orders: [orders.yaml, products.yaml]

  hosts:
    example.com: orders.yaml
    another.com: products.yaml
